resources:
- ../../base
namePrefix: prod-
patchesStrategicMerge:
- prod-configmap.yaml
- replica-count.yaml
configMapGenerator:
- literals:
  - TEXT1="Welcome to"
  - TEXT2="Production"
  name: rsvpconfig-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: teamcloudyuga/rsvpapp
  newName: nkhare/rsvpapp
  newTag: 6f8df7e720506b3c66b5aa67296f29d71304ca8e
